/**:
  ros__parameters:
    image_topic: "/kitti/camera/color/left/image_raw"
    weights_file: "/weights/fastflownet_kitti_192_640.engine" # Path to depth estimation file
    camera_frame: "cam2_link"
    base_frame: "base_link"
    original_image_height: 375
    original_image_width: 1242
